menu:
    # Archive: 
    Blog: /
    # Weibo: http://weibo.com/sunchongsheng
    GitHub: https://github.com/pinggod
    Rss: /atom.xml

mode: archives

favicon: https://midu.studio515.cn/logo/logo120.jpg
logo: https://midu.studio515.cn/logo/logo120.jpg

date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2015
